language: android
dist: trusty

env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.3
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=5

android:
  components:
    # Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # System images
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL

#    # Licenses
#    licenses:
#      - 'android-sdk-license-.+'

before_install:
  - chmod +x gradlew

#install:
#  travis_wait $ADB_INSTALL_TIMEOUT mvn install

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t "android-$ANDROID_API_LEVEL" --abi $ANDROID_ABI #--tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-audio -no-window -gpu off & # init &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  - travis_wait $ADB_INSTALL_TIMEOUT sleep 1800 &
  - android list target
  - ./gradlew connectedAndroidTest